// 'use client';
import { Inter } from "next/font/google";
import "./globals.css";
// import { SessionProvider } from 'next-auth/react';
import SessionProviderWrapper from '../component/empolyee/SessionProviderWrapper';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <SessionProvider>{children}</SessionProvider>
//       </body>
//     </html>
//   );
// }
